name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to AWS VM
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@muadmaalim.buzz << 'EOF'
            cd /home/ubuntu/fastapi-book-project
            git pull origin main
            docker-compose up --build -d
          EOF
